[project]
name = "flowerpower-ui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datastar-py>=0.4.4",
    "flowerpower[ext]>=0.10.6.3",
    "htpy>=25.5.0",
    "sanic>=25.3.0",
    "sanic-ext>=24.12.0",
    "uvicorn>=0.34.2",
]

[dependency-groups]
dev = [
    "ipython>=9.2.0",
]
